# Initiation and maintenance splitter

In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

import warnings
warnings.filterwarnings('ignore')

In [120]:
df = pd.read_csv('/home/jupyter/macuject_automated/data/master_all_stats.csv')
# ndf = ndf.rename(columns={"Patient::PatientBCID": "ID", "Patient::PatientGender": "gender", "Current age in 2020": "age"})
df.head()

,Unnamed: 0,gender,age,ExamGraph,InjectionType,NextTime,DaysFirst,actual_time,adherence_factor,running_ad,st_dev,ad_five,prev_vision,mean_vision,last_five,last_ten,last_three,std_vision,std_five,ID
0,0,Female,100,0.166667,Lucentis,13.0,668,12.0,1.0,0.67,0.4714,0.67,0.166667,0.19,0.16,0.15,0.18,0.0651,0.0416,0
1,1,Female,100,0.100000,Lucentis,4.0,843,12.0,1.0,0.62,0.4621,0.53,0.166667,0.19,0.17,0.15,0.17,0.0607,0.0000,0
2,2,Female,100,0.166667,Lucentis,4.0,871,4.0,1.0,0.69,0.4445,0.53,0.100000,0.18,0.15,0.15,0.14,0.0622,0.0267,0
3,3,Female,100,0.166667,Lucentis,4.0,899,4.0,1.0,0.73,0.4259,0.78,0.166667,0.18,0.15,0.15,0.14,0.0609,0.0267,0
4,4,Female,100,0.166667,Lucentis,4.0,927,4.0,1.0,0.76,0.4081,0.78,0.166667,0.18,0.15,0.16,0.14,0.0597,0.0267,0

In [121]:
df.shape

(28581, 20)

## Check what some intervals look like

In [122]:
intervals = check_id['actual_time']
intervals

27     3.57
28     4.00
29     4.00
30     4.00
31     4.00
32     4.57
33     9.86
34     4.00
35     6.00
36     4.00
37     4.00
38     4.00
39     4.00
40     6.00
41     6.00
42     6.00
43     6.86
44     5.14
45    13.29
46    10.00
47    11.00
48    10.00
49     9.00
50     8.86
51    10.14
52    10.00
53    12.00
54    12.00
55    12.00
56     9.86
Name: actual_time, dtype: float64

## Use biggest jump to determine where cutoff should be

In [123]:
# get the test dataframe: one patient
test_df = df[df['ID'] == 2]

### Doctest for biggest jump

In [124]:
# this function loops through a list to find the biggest jump 
def biggest_jump(interval_list):
    '''
    >>> biggest_jump(test_interval_list)
    14
    '''
    diff, index = 0, 0
    total = len(interval_list)
    for i in range(len(interval_list)-1):
        if interval_list[i+1] - interval_list[i] > diff and (i/total)> 0.2:
            diff = interval_list[i+1] - interval_list[i]
            index = i+1
        else:
            i += 1
    return index

In [125]:
import doctest
test_interval_list = [4,4,4,4,4,5,5,5,5,5,6,6,6,6,10,10,10,12,11,12]
doctest.testmod()

TestResults(failed=0, attempted=3)

In [126]:
intervals = check_id['actual_time'].tolist()
index = biggest_jump(intervals)
index

18

### Split the individual dataframe into initiation and maintenance, based on above index

In [127]:
test_df_initiation = test_df.iloc[:index,:]
test_df_maintenance = test_df.iloc[index:,:]
# test_df_initiation

## Split each patient's visits and add them to initiation or maintenance

In [128]:
# function to combine all of the above operations
def init_maint_splitter(patient_df):
    intervals = patient_df['actual_time'].tolist()
    index = biggest_jump(intervals)
    patient_df_initiation = patient_df.iloc[:index,:]
    patient_df_maintenance = patient_df.iloc[index:,:]
    return patient_df_initiation, patient_df_maintenance

In [129]:
test_init, test_maint = init_maint_splitter(test_df)
# test_init

In [130]:
# function to do the split to each patient, then concat
def master_dataframe():
    df = pd.read_csv('/home/jupyter/macuject_automated/data/master_all_stats.csv')
    id_list = df["ID"].unique()
    frames_init = []
    frames_maint = []
    for i in range(len(id_list)):
        patient_df = df[df['ID'] == i]
        try:
            init, maint = init_maint_splitter(patient_df)
            frames_init.append(init)
            frames_maint.append(maint)
        except:
            i += 1
    initiation_df = pd.concat(frames_init)
    maintenance_df = pd.concat(frames_maint)
    return initiation_df, maintenance_df

In [131]:
initiation_df, maintenance_df = master_dataframe()
initiation_df.shape, maintenance_df.shape

((16536, 20), (10685, 20))

In [132]:
initiation_df

,Unnamed: 0,gender,age,ExamGraph,InjectionType,NextTime,DaysFirst,actual_time,adherence_factor,running_ad,st_dev,ad_five,prev_vision,mean_vision,last_five,last_ten,last_three,std_vision,std_five,ID
0,0,Female,100,0.166667,Lucentis,13.0,668,12.0,1.0,0.67,0.4714,0.67,0.166667,0.19,0.16,0.15,0.18,0.0651,0.0416,0
1,1,Female,100,0.100000,Lucentis,4.0,843,12.0,1.0,0.62,0.4621,0.53,0.166667,0.19,0.17,0.15,0.17,0.0607,0.0000,0
2,2,Female,100,0.166667,Lucentis,4.0,871,4.0,1.0,0.69,0.4445,0.53,0.100000,0.18,0.15,0.15,0.14,0.0622,0.0267,0
3,3,Female,100,0.166667,Lucentis,4.0,899,4.0,1.0,0.73,0.4259,0.78,0.166667,0.18,0.15,0.15,0.14,0.0609,0.0267,0
4,4,Female,100,0.166667,Lucentis,4.0,927,4.0,1.0,0.76,0.4081,0.78,0.166667,0.18,0.15,0.16,0.14,0.0597,0.0267,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27206,27206,Male,76,1.500000,Lucentis,6.0,59,4.0,1.0,1.11,0.0000,1.11,1.200000,0.93,0.93,0.93,0.93,0.2667,0.2667,1115
27207,27207,Male,76,1.000000,Lucentis,6.0,157,8.0,1.0,1.04,0.0519,1.04,1.500000,1.22,1.22,1.22,1.40,0.3403,0.3403,1115
27208,27208,Male,76,1.000000,Lucentis,6.0,199,6.0,1.0,1.03,0.0476,1.03,1.000000,1.17,1.30,1.17,1.33,0.3165,0.2121,1115
27209,27209,Male,76,1.200000,Lucentis,8.0,339,8.0,1.0,0.97,0.1277,0.92,1.200000,1.20,1.18,1.20,1.35,0.2816,0.2046,1115
27210,27210,Male,76,1.000000,Lucentis,10.0,395,8.0,1.0,0.97,0.1199,0.92,1.200000,1.20,1.23,1.26,1.30,0.2655,0.1785,1115

## Save dataframes to data folders

In [133]:
initiation_df.to_csv('/home/jupyter/macuject_automated/data/initiation_df.csv')
maintenance_df.to_csv('/home/jupyter/macuject_automated/data/maintenance_df.csv')